package com.heypixel.heypixelmod.utils.localization;

import java.util.HashMap;
import java.util.Map;

public class ModuleLanguageManager {
    private static final Map<String, Map<String, String>> translations = new HashMap<>();
    private static String currentLanguage = "en_us";

    static {
        initEnglish();
        initChinese();
        initJapanese();
    }

    private static void initEnglish() {
        Map<String, String> en = new HashMap<>();
        en.put("module.autoplay", "AutoPlay");
        en.put("module.zhagntienancheststealer", "ZhagnTieNanChestStealer");
        en.put("module.antiweb", "AntiWeb");
        en.put("module.aura", "Aura");
        en.put("module.hud", "HUD");
        en.put("module.velocity", "Velocity");
        en.put("module.nametags", "NameTags");
        en.put("module.containerstealer", "ContainerStealer");
        en.put("module.inventorycleaner", "InventoryCleaner");
        en.put("module.scaffold", "Scaffold");
        en.put("module.itemphysics", "ItemPhysics");
        en.put("module.antibot", "AntiBot");
        en.put("module.sprint", "Sprint");
        en.put("module.targetstrafe", "TargetStrafe");
        en.put("module.chestesp", "ChestESP");
        en.put("module.clickgui", "ClickGUI");
        en.put("module.teams", "Teams");
        en.put("module.glow", "Glow");
        en.put("module.itemtracker", "ItemTracker");
        en.put("module.automlg", "AutoMLG");
        en.put("module.nojumpdelay", "NoJumpDelay");
        en.put("module.fastplace", "FastPlace");
        en.put("module.antifireball", "AntiFireball");
        en.put("module.stuck", "Stuck");
        en.put("module.scoreboardspoof", "ScoreboardSpoof");
        en.put("module.autotools", "AutoTools");
        en.put("module.viewclip", "ViewClip");
        en.put("module.disabler", "Disabler");
        en.put("module.debug", "Debug");
        en.put("module.projectile", "Projectile");
        en.put("module.timechanger", "TimeChanger");
        en.put("module.fullbright", "FullBright");
        en.put("module.nameprotect", "NameProtect");
        en.put("module.nohurtcam", "NoHurtCam");
        en.put("module.autoclicker", "AutoClicker");
        en.put("module.antiblindness", "AntiBlindness");
        en.put("module.antinausea", "AntiNausea");
        en.put("module.scoreboard", "Scoreboard");
        en.put("module.compass", "Compass");
        en.put("module.spammer", "Spammer");
        en.put("module.killsay", "KillSay");
        en.put("module.blink", "Blink");
        en.put("module.fastweb", "FastWeb");
        en.put("module.postprocess", "PostProcess");
        en.put("module.attackcrystal", "AttackCrystal");
        en.put("module.effectdisplay", "EffectDisplay");
        en.put("module.norender", "NoRender");
        en.put("module.itemtags", "ItemTags");
        en.put("module.safewalk", "SafeWalk");
        en.put("module.aimassist", "AimAssist");
        en.put("module.motionblur", "MotionBlur");
        en.put("module.language", "Language");
        en.put("module.inventorymove", "InventoryMove");
        en.put("module.bedaura", "BedAura");
        en.put("module.killerdetection", "KillerDetection");
        en.put("module.widget", "Widget");
        en.put("module.selfrescue", "SelfRescue");
        en.put("module.targethud", "TargetHUD");
        en.put("module.helper", "Helper");
        en.put("module.lowfire", "LowFire");
        en.put("module.bedplates", "BedPlates");
        en.put("module.autosoup", "AutoSoup");
        en.put("module.tntwarning", "TNTWarning");
        en.put("module.noslow", "NoSlow");
        en.put("module.longjump", "LongJump");
        en.put("module.safemode", "SafeMode");
        en.put("module.critical", "Critical");
        en.put("module.autoheal", "AutoHeal");
        en.put("module.moreknockback", "MoreKnockBack");
        en.put("module.protocol", "Protocol");
        en.put("module.ghosthand", "GhostHand");
        en.put("module.speed", "Speed");
        en.put("module.strafefix", "StrafeFix");
        en.put("module.midpearl", "MidPearl");
        en.put("module.autoweapon", "AutoWeapon");
        en.put("module.throwableaura", "ThrowableAura");
        en.put("module.backtrack", "BackTrack");
        en.put("module.BlueArchive", "BlueArchive");
        en.put("module.protocolmodule", "ProtocolModule");
        en.put("module.antikb", "Velocity");
        en.put("module.fakelag", "FakeLag");
        en.put("module.iqbooster", "IQBooster");
        en.put("module.animations", "Animations");
        en.put("module.autorod", "AutoRod");
        en.put("module.nofall", "NoFall");
        en.put("module.island", "Island");
        en.put("module.clip", "Clip");
        en.put("module.clip.desc", "Allows clipping through blocks");
        en.put("module.fly", "Fly");
        en.put("module.fly.desc", "Enables flight mode");
        en.put("module.killeffect", "Kill Effect");
        en.put("module.killeffect.desc", "Spawn effects when killing entities");
        en.put("module.noguiclose", "No GUI Close");
        en.put("module.noguiclose.desc", "Prevent GUI from closing when clicking outside");
        en.put("module.antiweb.desc", "Prevents getting stuck in cobwebs");
        en.put("module.aura.desc", "Automatically attacks nearby entities");
        en.put("module.hud.desc", "Displays information on screen");
        en.put("module.velocity.desc", "Reduces or eliminates knockback");
        en.put("module.nametags.desc", "Customizes name tag display");
        en.put("module.containerstealer.desc", "Automatically steals from containers");
        en.put("module.inventorycleaner.desc", "Automatically cleans inventory");
        en.put("module.scaffold.desc", "Automatically places blocks under you");
        en.put("module.itemphysics.desc", "Modifies item physics");
        en.put("module.antibot.desc", "Detects and avoids bots");
        en.put("module.sprint.desc", "Automatically sprints");
        en.put("module.targetstrafe.desc", "Strafes around targets");
        en.put("module.chestesp.desc", "Highlights chests");
        en.put("module.clickgui.desc", "Click GUI interface");
        en.put("module.teams.desc", "Team management");
        en.put("module.glow.desc", "Adds glow effects");
        en.put("module.itemtracker.desc", "Tracks item locations");
        en.put("module.automlg.desc", "Automatically performs MLG");
        en.put("module.nojumpdelay.desc", "Removes jump cooldown");
        en.put("module.fastplace.desc", "Places blocks quickly");
        en.put("module.antifireball.desc", "Defends against fireballs");
        en.put("module.stuck.desc", "Fixes stuck issues");
        en.put("module.scoreboardspoof.desc", "Spoofs scoreboard display");
        en.put("module.autotools.desc", "Automatically selects best tool");
        en.put("module.viewclip.desc", "View clipping settings");
        en.put("module.disabler.desc", "Disables certain features");
        en.put("module.debug.desc", "Debug tools");
        en.put("module.projectile.desc", "Projectile settings");
        en.put("module.timechanger.desc", "Changes game time");
        en.put("module.fullbright.desc", "Maximum brightness");
        en.put("module.nameprotect.desc", "Protects player names");
        en.put("module.nohurtcam.desc", "Removes hurt camera shake");
        en.put("module.autoclicker.desc", "Automatically clicks mouse");
        en.put("module.antiblindness.desc", "Resists blindness effect");
        en.put("module.antinausea.desc", "Resists nausea effect");
        en.put("module.scoreboard.desc", "Scoreboard display");
        en.put("module.compass.desc", "Compass functionality");
        en.put("module.spammer.desc", "Automatically sends messages");
        en.put("module.killsay.desc", "Auto chat after kills");
        en.put("module.blink.desc", "Pauses and resumes packet sending");
        en.put("module.fastweb.desc", "Quickly handles cobwebs");
        en.put("module.postprocess.desc", "Post-processing effects");
        en.put("module.attackcrystal.desc", "Automatically attacks end crystals");
        en.put("module.effectdisplay.desc", "Displays status effects");
        en.put("module.norender.desc", "Disables certain rendering");
        en.put("module.itemtags.desc", "Item tag display");
        en.put("module.safewalk.desc", "Safe walking mode");
        en.put("module.aimassist.desc", "Aim assistance");
        en.put("module.motionblur.desc", "Motion blur effect");
        en.put("module.language.desc", "Changes module language");
        en.put("module.inventorymove.desc", "Move while inventory is open");
        en.put("module.bedaura.desc", "Automatically attacks beds");
        en.put("module.killerdetection.desc", "Detects killer players");
        en.put("module.widget.desc", "Widget management");
        en.put("module.selfrescue.desc", "Self rescue functionality");
        en.put("module.targethud.desc", "Target HUD display");
        en.put("module.helper.desc", "Game helper");
        en.put("module.lowfire.desc", "Reduces fire effects");
        en.put("module.bedplates.desc", "Bed plate display");
        en.put("module.autosoup.desc", "Automatically eats soup");
        en.put("module.tntwarning.desc", "TNT explosion warning");
        en.put("module.noslow.desc", "Prevents slowing effects");
        en.put("module.longjump.desc", "Long distance jumping");
        en.put("module.safemode.desc", "Safe mode");
        en.put("module.critical.desc", "Critical hit settings");
        en.put("module.autoheal.desc", "Automatically heals");
        en.put("module.moreknockback.desc", "Increases knockback");
        en.put("module.protocol.desc", "Protocol settings");
        en.put("module.ghosthand.desc", "Ghost hand functionality");
        en.put("module.speed.desc", "Increases movement speed");
        en.put("module.strafefix.desc", "Fixes strafing issues");
        en.put("module.midpearl.desc", "Mid-range pearl teleport");
        en.put("module.autoweapon.desc", "Automatically selects weapons");
        en.put("module.throwableaura.desc", "Automatically throws items");
        en.put("module.backtrack.desc", "Backtrack functionality");
        en.put("module.protocolmodule.desc", "Protocol module");
        en.put("module.antikb.desc", "Prevents knockback");
        en.put("module.fakelag.desc", "Fake lag");
        en.put("module.iqbooster.desc", "Improves game IQ");
        en.put("module.animations.desc", "Animation effects");
        en.put("module.autorod.desc", "Automatically uses fishing rod");
        en.put("module.nofall.desc", "Prevents fall damage");
        en.put("module.island.desc", "Island related features");
        en.put("module.fakelag.desc", "Simulates network lag by delaying packets");
        en.put("module.delaytrack", "DelayTrack");
        en.put("module.delaytrack.desc", "Simulates network delay for packets");
        en.put("module.camera", "Camera");
        en.put("module.camera.desc", "Camera settings and controls");
        en.put("category.combat", "Combat");
        en.put("category.movement", "Movement");
        en.put("category.render", "Render");
        en.put("category.exploit", "Exploit");
        en.put("category.misc", "Misc");
        en.put("category.world", "World");
        en.put("category.player", "Player");

        en.put("setting.enabled", "Enabled");
        en.put("setting.disabled", "Disabled");
        en.put("setting.on", "On");
        en.put("setting.off", "Off");

        translations.put("en_us", en);
    }

    private static void initChinese() {
        Map<String, String> zh = new HashMap<>();
        zh.put("module.autoplay", "自动游玩");
        zh.put("module.antiweb", "反蜘蛛网");
        zh.put("module.aura", "杀戮光环");
        zh.put("module.hud", "HUD");
        zh.put("module.velocity", "防击退");
        zh.put("module.nametags", "名称标签");
        zh.put("module.zhagntienancheststealer", "张铁楠箱子窃取");
        zh.put("module.containerstealer", "箱子窃取");
        zh.put("module.inventorycleaner", "库存清理");
        zh.put("module.scaffold", "脚手架");
        zh.put("module.itemphysics", "物品物理");
        zh.put("module.antibot", "反机器人");
        zh.put("module.sprint", "自动奔跑");
        zh.put("module.targetstrafe", "目标环绕");
        zh.put("module.delaytrack", "延迟追踪");
        zh.put("module.delaytrack.desc", "模拟数据包的网络延迟");
        zh.put("module.camera", "相机");
        zh.put("module.camera.desc", "相机设置和控制");
        zh.put("module.BlueArchive", "蓝色档案");
        zh.put("module.chestesp", "箱子ESP");
        zh.put("module.clickgui", "点击GUI");
        zh.put("module.teams", "队伍");
        zh.put("module.glow", "发光效果");
        zh.put("module.itemtracker", "物品追踪");
        zh.put("module.automlg", "自动MLG");
        zh.put("module.nojumpdelay", "无跳跃延迟");
        zh.put("module.fastplace", "快速放置");
        zh.put("module.antifireball", "防火球");
        zh.put("module.stuck", "卡顿修复");
        zh.put("module.scoreboardspoof", "记分板欺骗");
        zh.put("module.autotools", "自动工具");
        zh.put("module.viewclip", "视角裁剪");
        zh.put("module.disabler", "禁用器");
        zh.put("module.debug", "调试");
        zh.put("module.projectile", "抛射物");
        zh.put("module.timechanger", "时间更改");
        zh.put("module.fullbright", "全亮");
        zh.put("module.nameprotect", "名称保护");
        zh.put("module.nohurtcam", "无受伤晃动");
        zh.put("module.autoclicker", "自动点击");
        zh.put("module.antiblindness", "抗失明");
        zh.put("module.antinausea", "抗恶心");
        zh.put("module.scoreboard", "记分板");
        zh.put("module.compass", "指南针");
        zh.put("module.spammer", "垃圾话");
        zh.put("module.killsay", "击杀发言");
        zh.put("module.blink", "闪烁");
        zh.put("module.fastweb", "快速蜘蛛网");
        zh.put("module.postprocess", "后处理");
        zh.put("module.attackcrystal", "攻击水晶");
        zh.put("module.effectdisplay", "效果显示");
        zh.put("module.norender", "无渲染");
        zh.put("module.itemtags", "物品标签");
        zh.put("module.safewalk", "安全行走");
        zh.put("module.aimassist", "瞄准辅助");
        zh.put("module.motionblur", "动态模糊");
        zh.put("module.language", "语言");
        zh.put("module.inventorymove", "库存移动");
        zh.put("module.bedaura", "床光环");
        zh.put("module.killerdetection", "杀手检测");
        zh.put("module.widget", "小部件");
        zh.put("module.selfrescue", "自救");
        zh.put("module.targethud", "目标HUD");
        zh.put("module.helper", "助手");
        zh.put("module.lowfire", "低火");
        zh.put("module.bedplates", "床板");
        zh.put("module.autosoup", "自动汤");
        zh.put("module.tntwarning", "TNT警告");
        zh.put("module.noslow", "无减速");
        zh.put("module.longjump", "长跳");
        zh.put("module.safemode", "安全模式");
        zh.put("module.critical", "暴击");
        zh.put("module.autoheal", "自动治疗");
        zh.put("module.moreknockback", "更多击退");
        zh.put("module.protocol", "协议");
        zh.put("module.ghosthand", "幽灵手");
        zh.put("module.speed", "速度");
        zh.put("module.strafefix", "扫射修复");
        zh.put("module.midpearl", "中珍珠");
        zh.put("module.autoweapon", "自动武器");
        zh.put("module.throwableaura", "投掷物光环");
        zh.put("module.backtrack", "回溯");
        zh.put("module.protocolmodule", "协议模块");
        zh.put("module.antikb", "防击退");
        zh.put("module.fakelag", "假延迟");
        zh.put("module.iqbooster", "智商提升");
        zh.put("module.animations", "动画");
        zh.put("module.autorod", "自动鱼竿");
        zh.put("module.nofall", "无摔落");
        zh.put("module.island", "岛屿");
        zh.put("module.clip", "穿墙");
        zh.put("module.clip.desc", "允许穿墙通过方块");
        zh.put("module.fly", "飞行");
        zh.put("module.fly.desc", "启用飞行模式");
        zh.put("module.killeffect", "击杀特效");
        zh.put("module.killeffect.desc", "击杀实体时生成特效");
        zh.put("module.noguiclose", "GUI保持开启");
        zh.put("module.noguiclose.desc", "点击外部时防止GUI关闭");
        zh.put("module.antiweb.desc", "防止被蜘蛛网困住");
        zh.put("module.aura.desc", "自动攻击范围内的实体");
        zh.put("module.hud.desc", "在屏幕上显示信息");
        zh.put("module.velocity.desc", "减少或消除击退效果");
        zh.put("module.nametags.desc", "自定义名称标签显示");
        zh.put("module.containerstealer.desc", "自动从容器中拿取物品");
        zh.put("module.inventorycleaner.desc", "自动清理库存");
        zh.put("module.scaffold.desc", "自动在脚下放置方块");
        zh.put("module.itemphysics.desc", "修改物品物理效果");
        zh.put("module.antibot.desc", "检测和避免机器人");
        zh.put("module.sprint.desc", "自动奔跑");
        zh.put("module.targetstrafe.desc", "围绕目标移动");
        zh.put("module.chestesp.desc", "高亮显示箱子");
        zh.put("module.clickgui.desc", "点击GUI界面");
        zh.put("module.teams.desc", "队伍管理");
        zh.put("module.glow.desc", "添加发光效果");
        zh.put("module.itemtracker.desc", "追踪物品位置");
        zh.put("module.automlg.desc", "自动MLG操作");
        zh.put("module.nojumpdelay.desc", "移除跳跃冷却");
        zh.put("module.fastplace.desc", "快速放置方块");
        zh.put("module.antifireball.desc", "防御火球攻击");
        zh.put("module.stuck.desc", "修复卡顿问题");
        zh.put("module.scoreboardspoof.desc", "欺骗记分板显示");
        zh.put("module.autotools.desc", "自动选择最佳工具");
        zh.put("module.viewclip.desc", "视角裁剪设置");
        zh.put("module.disabler.desc", "禁用某些功能");
        zh.put("module.debug.desc", "调试工具");
        zh.put("module.projectile.desc", "抛射物相关设置");
        zh.put("module.timechanger.desc", "更改游戏时间");
        zh.put("module.fullbright.desc", "最大亮度");
        zh.put("module.nameprotect.desc", "保护玩家名称");
        zh.put("module.nohurtcam.desc", "移除受伤晃动效果");
        zh.put("module.autoclicker.desc", "自动点击鼠标");
        zh.put("module.antiblindness.desc", "抵抗失明效果");
        zh.put("module.antinausea.desc", "抵抗恶心效果");
        zh.put("module.scoreboard.desc", "记分板显示");
        zh.put("module.compass.desc", "指南针功能");
        zh.put("module.spammer.desc", "自动发送消息");
        zh.put("module.killsay.desc", "击杀后自动发言");
        zh.put("module.blink.desc", "暂停和恢复数据包发送");
        zh.put("module.fastweb.desc", "快速处理蜘蛛网");
        zh.put("module.postprocess.desc", "后处理效果");
        zh.put("module.attackcrystal.desc", "自动攻击末影水晶");
        zh.put("module.effectdisplay.desc", "显示状态效果");
        zh.put("module.norender.desc", "禁用某些渲染");
        zh.put("module.itemtags.desc", "物品标签显示");
        zh.put("module.safewalk.desc", "安全行走模式");
        zh.put("module.aimassist.desc", "瞄准辅助功能");
        zh.put("module.motionblur.desc", "动态模糊效果");
        zh.put("module.language.desc", "更改模块语言");
        zh.put("module.inventorymove.desc", "在打开库存时移动");
        zh.put("module.bedaura.desc", "自动攻击床");
        zh.put("module.killerdetection.desc", "检测杀手玩家");
        zh.put("module.widget.desc", "小部件管理");
        zh.put("module.selfrescue.desc", "自救功能");
        zh.put("module.targethud.desc", "目标HUD显示");
        zh.put("module.helper.desc", "游戏助手");
        zh.put("module.lowfire.desc", "降低火焰效果");
        zh.put("module.bedplates.desc", "床板显示");
        zh.put("module.autosoup.desc", "自动喝汤");
        zh.put("module.tntwarning.desc", "TNT爆炸警告");
        zh.put("module.noslow.desc", "防止减速效果");
        zh.put("module.longjump.desc", "长距离跳跃");
        zh.put("module.safemode.desc", "安全模式");
        zh.put("module.critical.desc", "暴击设置");
        zh.put("module.autoheal.desc", "自动治疗");
        zh.put("module.moreknockback.desc", "增加击退效果");
        zh.put("module.protocol.desc", "协议相关设置");
        zh.put("module.ghosthand.desc", "幽灵手功能");
        zh.put("module.speed.desc", "增加移动速度");
        zh.put("module.strafefix.desc", "修复扫射问题");
        zh.put("module.midpearl.desc", "中距离珍珠传送");
        zh.put("module.autoweapon.desc", "自动选择武器");
        zh.put("module.throwableaura.desc", "自动投掷物品");
        zh.put("module.backtrack.desc", "回溯功能");
        zh.put("module.protocolmodule.desc", "协议模块");
        zh.put("module.antikb.desc", "防止击退");
        zh.put("module.fakelag.desc", "虚假延迟");
        zh.put("module.iqbooster.desc", "提升游戏智商");
        zh.put("module.animations.desc", "动画效果");
        zh.put("module.autorod.desc", "自动使用鱼竿");
        zh.put("module.nofall.desc", "防止摔落伤害");
        zh.put("module.island.desc", "岛屿相关功能");
        zh.put("module.fakelag.desc", "通过延迟数据包模拟网络延迟");
        zh.put("category.combat", "战斗");
        zh.put("category.movement", "移动");
        zh.put("category.render", "渲染");
        zh.put("category.exploit", "利用");
        zh.put("category.misc", "杂项");
        zh.put("category.world", "世界");
        zh.put("category.player", "玩家");

        zh.put("setting.enabled", "已启用");
        zh.put("setting.disabled", "已禁用");
        zh.put("setting.on", "开");
        zh.put("setting.off", "关");

        translations.put("zh_cn", zh);
    }

    private static void initJapanese() {
        Map<String, String> ja = new HashMap<>();

        ja.put("module.autoplay", "自動再生");
        ja.put("module.antiweb", "反ウェブ");
        ja.put("module.aura", "キルオーラ");
        ja.put("module.hud", "HUD");
        ja.put("module.velocity", "ノックバック軽減");
        ja.put("module.nametags", "ネームタグ");
        ja.put("module.zhagntienancheststealer", "張鉄男チェストスティーラー");
        ja.put("module.containerstealer", "コンテナ窃盗");
        ja.put("module.inventorycleaner", "インベントリクリーナー");
        ja.put("module.scaffold", "足場");
        ja.put("module.itemphysics", "アイテム物理");
        ja.put("module.antibot", "アンチボット");
        ja.put("module.sprint", "自動スプリント");
        ja.put("module.targetstrafe", "ターゲットストラフェ");
        ja.put("module.chestesp", "チェストESP");
        ja.put("module.clickgui", "クリックGUI");
        ja.put("module.teams", "チーム");
        ja.put("module.glow", "発光効果");
        ja.put("module.itemtracker", "アイテムトラッカー");
        ja.put("module.automlg", "自動MLG");
        ja.put("module.nojumpdelay", "ジャンプ遅延無効");
        ja.put("module.fastplace", "高速設置");
        ja.put("module.antifireball", "反ファイアボール");
        ja.put("module.BlueArchive", "ブルーアーカイブ");
        ja.put("module.stuck", "スタック修正");
        ja.put("module.scoreboardspoof", "スコアボード偽装");
        ja.put("module.autotools", "自動ツール");
        ja.put("module.viewclip", "ビュークリップ");
        ja.put("module.disabler", "ディセイブラー");
        ja.put("module.debug", "デバッグ");
        ja.put("module.projectile", "発射体");
        ja.put("module.timechanger", "時間変更");
        ja.put("module.fullbright", "フルブライト");
        ja.put("module.nameprotect", "ネーム保護");
        ja.put("module.nohurtcam", "ハートカム無効");
        ja.put("module.autoclicker", "自動クリック");
        ja.put("module.antiblindness", "盲目抵抗");
        ja.put("module.antinausea", "吐き気抵抗");
        ja.put("module.scoreboard", "スコアボード");
        ja.put("module.compass", "コンパス");
        ja.put("module.spammer", "スパマー");
        ja.put("module.killsay", "キルセイ");
        ja.put("module.blink", "ブリンク");
        ja.put("module.fastweb", "高速ウェブ");
        ja.put("module.postprocess", "ポストプロセス");
        ja.put("module.attackcrystal", "クリスタル攻撃");
        ja.put("module.effectdisplay", "効果表示");
        ja.put("module.norender", "レンダー無効");
        ja.put("module.itemtags", "アイテムタグ");
        ja.put("module.safewalk", "安全歩行");
        ja.put("module.aimassist", "エイムアシスト");
        ja.put("module.motionblur", "モーションブラー");
        ja.put("module.language", "言語");
        ja.put("module.inventorymove", "インベントリ移動");
        ja.put("module.bedaura", "ベッドオーラ");
        ja.put("module.killerdetection", "キラー検出");
        ja.put("module.widget", "ウィジェット");
        ja.put("module.selfrescue", "自己救助");
        ja.put("module.targethud", "ターゲットHUD");
        ja.put("module.helper", "ヘルパー");
        ja.put("module.lowfire", "低火");
        ja.put("module.bedplates", "ベッドプレート");
        ja.put("module.autosoup", "自動スープ");
        ja.put("module.tntwarning", "TNT警告");
        ja.put("module.noslow", "減速無効");
        ja.put("module.longjump", "ロングジャンプ");
        ja.put("module.safemode", "セーフモード");
        ja.put("module.critical", "クリティカル");
        ja.put("module.autoheal", "自動回復");
        ja.put("module.moreknockback", "更多ノックバック");
        ja.put("module.protocol", "プロトコル");
        ja.put("module.ghosthand", "ゴーストハンド");
        ja.put("module.speed", "速度");
        ja.put("module.strafefix", "ストラフェ修正");
        ja.put("module.midpearl", "ミッドパール");
        ja.put("module.autoweapon", "自動武器");
        ja.put("module.throwableaura", "投擲オーラ");
        ja.put("module.backtrack", "バックトラック");
        ja.put("module.protocolmodule", "プロトコルモジュール");
        ja.put("module.antikb", "反KB");
        ja.put("module.fakelag", "フェイクラグ");
        ja.put("module.iqbooster", "IQブースター");
        ja.put("module.animations", "アニメーション");
        ja.put("module.autorod", "自動ロッド");
        ja.put("module.nofall", "落下無効");
        ja.put("module.island", "島");
        ja.put("module.clip", "クリップ");
        ja.put("module.clip.desc", "ブロックを通り抜ける");
        ja.put("module.fly", "フライ");
        ja.put("module.fly.desc", "飛行モードを有効化");
        ja.put("module.antiweb.desc", "クモの巣に引っかかるのを防ぐ");
        ja.put("module.aura.desc", "範囲内のエンティティを自動攻撃");
        ja.put("module.hud.desc", "画面上に情報を表示");
        ja.put("module.velocity.desc", "ノックバックを軽減または無効化");
        ja.put("module.nametags.desc", "ネームタグ表示をカスタマイズ");
        ja.put("module.containerstealer.desc", "コンテナから自動でアイテムを取得");
        ja.put("module.inventorycleaner.desc", "インベントリを自動整理");
        ja.put("module.scaffold.desc", "自動的にブロックを設置");
        ja.put("module.itemphysics.desc", "アイテム物理を変更");
        ja.put("module.antibot.desc", "ボットを検出して回避");
        ja.put("module.sprint.desc", "自動的に走る");
        ja.put("module.targetstrafe.desc", "ターゲットの周りを移動");
        ja.put("module.chestesp.desc", "チェストをハイライト表示");
        ja.put("module.clickgui.desc", "クリックGUIインターフェース");
        ja.put("module.teams.desc", "チーム管理");
        ja.put("module.glow.desc", "発光効果を追加");
        ja.put("module.itemtracker.desc", "アイテム位置を追跡");
        ja.put("module.automlg.desc", "自動MLG操作");
        ja.put("module.nojumpdelay.desc", "ジャンプクールダウンを削除");
        ja.put("module.fastplace.desc", "高速でブロックを設置");
        ja.put("module.antifireball.desc", "ファイアボール攻撃を防御");
        ja.put("module.stuck.desc", "スタック問題を修正");
        ja.put("module.scoreboardspoof.desc", "スコアボード表示を偽装");
        ja.put("module.autotools.desc", "最適なツールを自動選択");
        ja.put("module.viewclip.desc", "ビュークリッピング設定");
        ja.put("module.disabler.desc", "特定の機能を無効化");
        ja.put("module.debug.desc", "デバッグツール");
        ja.put("module.projectile.desc", "発射体設定");
        ja.put("module.timechanger.desc", "ゲーム時間を変更");
        ja.put("module.fullbright.desc", "最大輝度");
        ja.put("module.nameprotect.desc", "プレイヤー名を保護");
        ja.put("module.nohurtcam.desc", "ダメージカメラシェイクを削除");
        ja.put("module.autoclicker.desc", "自動的にマウスクリック");
        ja.put("module.antiblindness.desc", "盲目効果を抵抗");
        ja.put("module.antinausea.desc", "吐き気効果を抵抗");
        ja.put("module.scoreboard.desc", "スコアボード表示");
        ja.put("module.compass.desc", "コンパス機能");
        ja.put("module.spammer.desc", "自動的にメッセージを送信");
        ja.put("module.killsay.desc", "キル後に自動発言");
        ja.put("module.blink.desc", "パケット送信を一時停止/再開");
        ja.put("module.fastweb.desc", "クモの巣を高速処理");
        ja.put("module.postprocess.desc", "ポストプロセス効果");
        ja.put("module.attackcrystal.desc", "エンドクリスタルを自動攻撃");
        ja.put("module.effectdisplay.desc", "ステータス効果を表示");
        ja.put("module.norender.desc", "特定のレンダリングを無効化");
        ja.put("module.itemtags.desc", "アイテムタグ表示");
        ja.put("module.safewalk.desc", "安全歩行モード");
        ja.put("module.aimassist.desc", "エイムアシスト");
        ja.put("module.motionblur.desc", "モーションブラー効果");
        ja.put("module.language.desc", "モジュール言語を変更");
        ja.put("module.inventorymove.desc", "インベントリ開閉中に移動");
        ja.put("module.bedaura.desc", "ベッドを自動攻撃");
        ja.put("module.killerdetection.desc", "キラープレイヤーを検出");
        ja.put("module.widget.desc", "ウィジェット管理");
        ja.put("module.selfrescue.desc", "自己救助機能");
        ja.put("module.targethud.desc", "ターゲットHUD表示");
        ja.put("module.helper.desc", "ゲームヘルパー");
        ja.put("module.lowfire.desc", "火炎効果を低減");
        ja.put("module.bedplates.desc", "ベッドプレート表示");
        ja.put("module.autosoup.desc", "自動的にスープを飲む");
        ja.put("module.tntwarning.desc", "TNT爆発警告");
        ja.put("module.noslow.desc", "減速効果を防止");
        ja.put("module.longjump.desc", "長距離ジャンプ");
        ja.put("module.safemode.desc", "セーフモード");
        ja.put("module.critical.desc", "クリティカル設定");
        ja.put("module.autoheal.desc", "自動回復");
        ja.put("module.moreknockback.desc", "ノックバックを増加");
        ja.put("module.protocol.desc", "プロトコル設定");
        ja.put("module.ghosthand.desc", "ゴーストハンド機能");
        ja.put("module.speed.desc", "移動速度を向上");
        ja.put("module.strafefix.desc", "ストラフェ問題を修正");
        ja.put("module.midpearl.desc", "中距離パールテレポート");
        ja.put("module.autoweapon.desc", "自動的に武器を選択");
        ja.put("module.throwableaura.desc", "自動的にアイテムを投擲");
        ja.put("module.backtrack.desc", "バックトラック機能");
        ja.put("module.protocolmodule.desc", "プロトコルモジュール");
        ja.put("module.antikb.desc", "ノックバックを防止");
        ja.put("module.fakelag.desc", "偽のラグ");
        ja.put("module.iqbooster.desc", "ゲームIQを向上");
        ja.put("module.animations.desc", "アニメーション効果");
        ja.put("module.autorod.desc", "自動的に釣り竿を使用");
        ja.put("module.nofall.desc", "落下ダメージを防止");
        ja.put("module.island.desc", "島関連機能");
        ja.put("module.killeffect", "キルエフェクト");
        ja.put("module.killeffect.desc", "エンティティを倒した時にエフェクトを発生");
        ja.put("module.noguiclose", "GUI閉じない");
        ja.put("module.noguiclose.desc", "外部クリックでGUIが閉じるのを防止");
        ja.put("category.combat", "戦闘");
        ja.put("category.movement", "移動");
        ja.put("category.render", "レンダー");
        ja.put("category.exploit", "悪用");
        ja.put("category.misc", "その他");
        ja.put("module.delaytrack", "ディレイトラック");
        ja.put("module.delaytrack.desc", "パケットのネットワーク遅延をシミュレート");
        ja.put("module.camera", "カメラ");
        ja.put("module.camera.desc", "カメラ設定と制御");
        ja.put("category.world", "ワールド");
        ja.put("category.player", "プレイヤー");
        ja.put("setting.enabled", "有効");
        ja.put("setting.disabled", "無効");
        ja.put("setting.on", "オン");
        ja.put("setting.off", "オフ");
        ja.put("module.fakelag.desc", "パケットを遅延させてネットワークラグをシミュレート");

        translations.put("ja_jp", ja);
    }

    public static void setLanguage(String languageCode) {
        if (translations.containsKey(languageCode)) {
            currentLanguage = languageCode;
        }
    }

    public static String getTranslation(String key) {
        Map<String, String> langTranslations = translations.get(currentLanguage);
        if (langTranslations != null && langTranslations.containsKey(key)) {
            return langTranslations.get(key);
        }

        // 回退到英语
        Map<String, String> enTranslations = translations.get("en_us");
        if (enTranslations != null && enTranslations.containsKey(key)) {
            return enTranslations.get(key);
        }

        return key;
    }

    public static String getCurrentLanguage() {
        return currentLanguage;
    }

    public static String getLanguageDisplayName(String code) {
        switch (code) {
            case "zh_cn": return "简体中文";
            case "ja_jp": return "日本語";
            case "en_us":
            default: return "English";
        }
    }
}